// Class automatically generated by Dev-C++ New Class wizard

#ifndef KEYBOX_H
#define KEYBOX_H

#define DEVICEID_OFFSET 18
#define DEVICEID_LENGTH 23
#define DEVICEID_SIZE_IN_KEYBOX 32
#define KEY_OFFSET 48
#define KEY_LENGTH 32
#define ID_OFFSET 90
#define ID_LENGTH 144
#define MAGIC_OFFSET 246
#define MAGIC_LENGTH 8
#define CRC_OFFSET 267
#define CRC_LENGTH 8

/*
 * present an android keybox
 */
class Keybox
{
	public:
		// class constructor
		Keybox();
		Keybox(const char* xml);
		// class destructor
		~Keybox();
		
		void init( const char* xml);
		void getDeviceID(char* deviceID);
		int convertToCsv(char* out);
		
    protected:
        void charToHex(char src, char* high, char* low);
		
	protected:
        char mDeviceID[DEVICEID_SIZE_IN_KEYBOX];
        char mKey[KEY_LENGTH];
        char mID[ID_LENGTH];
        char mMagic[MAGIC_LENGTH];
        char mCRC[CRC_LENGTH];
};

#endif // KEYBOX_H
